### ISSUE TITLE
本書中の「Crystal」の表記について

### ISSUE THREAD

**Issue by at-grandpa** [crystal-jp/techbookfest4#4]
「Crystal」の表記ついて、下記が考えられますがいかがでしょうか？

* `Crystal`
  * 一番一般的。READMEやdocs等もこの表記であり、説明に出てくる他の言語の名前（`Ruby`など）もこの表記。
* `crystal`
  * 次にありそうなのがこれかと。
* `CRYSTAL`
  * 公式ロゴは全て大文字。

個人的には、「読み物としては `Crystal` ですよね」なんですが、一応認識を合わせたほうが良いと思ったのでissueたてました！

**Comment by at-grandpa** [comment]
例えば、「表記ってどうなんだっけ？」と思ったら、 「 https://crystal-lang.org/docs/ を基準とする」とかでも良さそうですかね。

**Comment by MakeNowJust** [comment]
プログラミング言語としては「Crystal」ですが、コマンド名としては「crystal」です。他のケースは無いと思います。Redpenのルールに追加しておきます。

**Comment by at-grandpa** [comment]
ああ、そうですね！コマンドがありました。

Redpen追加たすかりますーmm
